[package]
name = "neutraltemplate"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "neutraltemplate"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
neutralts = "1.2.9"
serde_json = "1.0"
